// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Theo_Doi_Chi_Phi.Models;

#nullable disable

namespace Theo_Doi_Chi_Phi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230112100127_Khoi Tao Ban Dau")]
    partial class KhoiTaoBanDau
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Theo_Doi_Chi_Phi.Models.Category", b =>
                {
                    b.Property<int>("So_Danh_Muc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("So_Danh_Muc"), 1L, 1);

                    b.Property<string>("Bieu_Tuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Loai")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Tieu_De")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("So_Danh_Muc");

                    b.ToTable("Danh_muc");
                });

            modelBuilder.Entity("Theo_Doi_Chi_Phi.Models.Transaction", b =>
                {
                    b.Property<int>("Id_Giao_Dich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Giao_Dich"), 1L, 1);

                    b.Property<int?>("CategorySo_Danh_Muc")
                        .HasColumnType("int");

                    b.Property<string>("Ghi_Chu")
                        .HasColumnType("nvarchar(75)");

                    b.Property<int>("Gia_Tri")
                        .HasColumnType("int");

                    b.Property<int>("So_Danh_Muc")
                        .HasColumnType("int");

                    b.Property<DateTime>("Thoi_gian")
                        .HasColumnType("datetime2");

                    b.HasKey("Id_Giao_Dich");

                    b.HasIndex("CategorySo_Danh_Muc");

                    b.ToTable("Giao_dich");
                });

            modelBuilder.Entity("Theo_Doi_Chi_Phi.Models.Transaction", b =>
                {
                    b.HasOne("Theo_Doi_Chi_Phi.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategorySo_Danh_Muc");

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
