// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Theo_Dõi_Chi_Phí.Models;

#nullable disable

namespace Theo_Dõi_Chi_Phí.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230113042636_DU LIEU KHOI NGUYEN")]
    partial class DULIEUKHOINGUYEN
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Theo_Dõi_Chi_Phí.Models.Category", b =>
                {
                    b.Property<int>("Số_danh_mục")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Số_danh_mục"), 1L, 1);

                    b.Property<string>("Biểu_tượng")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Loại")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Tiêu_đề")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Số_danh_mục");

                    b.ToTable("Danh_mục");
                });

            modelBuilder.Entity("Theo_Dõi_Chi_Phí.Models.Transaction", b =>
                {
                    b.Property<int>("Mã_giao_dịch")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mã_giao_dịch"), 1L, 1);

                    b.Property<int?>("CategorySố_danh_mục")
                        .HasColumnType("int");

                    b.Property<string>("Ghi_chú")
                        .HasColumnType("nvarchar(75)");

                    b.Property<int>("Giá_trị")
                        .HasColumnType("int");

                    b.Property<int>("Số_danh_mục")
                        .HasColumnType("int");

                    b.Property<DateTime>("Thời_gian")
                        .HasColumnType("datetime2");

                    b.HasKey("Mã_giao_dịch");

                    b.HasIndex("CategorySố_danh_mục");

                    b.ToTable("Giao_dịch");
                });

            modelBuilder.Entity("Theo_Dõi_Chi_Phí.Models.Transaction", b =>
                {
                    b.HasOne("Theo_Dõi_Chi_Phí.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategorySố_danh_mục");

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
